[package]
name = "plakait-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
axum-server = { version = "0.4", features = ["tls-rustls"] }
axum-macros = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3"}
config = "0.13"
openai = "1.0.0-alpha.8"
tower-http = { version = "0.4", features = ["cors", "timeout"] }
once_cell = "1.17"
uuid = { version = "1.3", features = ["v4", "serde"] }
anyhow = "1.0"

[dev-dependencies]
tower = { version = "0.4", features = ["util"] }
hyper = { version = "0.14", features = ["full"] }